// <auto-generated />
using MarcaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarcaApi.Migrations
{
    [DbContext(typeof(MarcaApiContext))]
    partial class MarcaApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("MarcaApi.Models.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnoFundacao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaisOrigem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slogan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Marcas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnoFundacao = 1969,
                            Descricao = "Empresa líder no setor de tecnologia, especializada em dispositivos eletrônicos e soluções digitais.",
                            Nome = "Samsung",
                            PaisOrigem = "Coreia do Sul",
                            Setor = "Tecnologia",
                            Slogan = "Faça o que você não pode",
                            Website = "https://www.samsung.com/br/"
                        },
                        new
                        {
                            Id = 2,
                            AnoFundacao = 1976,
                            Descricao = "Empresa líder no desenvolvimento de hardware e software inovadores.",
                            Nome = "Apple",
                            PaisOrigem = "EUA",
                            Setor = "Tecnologia",
                            Slogan = "Think Different",
                            Website = "https://www.apple.com/"
                        },
                        new
                        {
                            Id = 3,
                            AnoFundacao = 1946,
                            Descricao = "Especializada em eletrônicos de consumo, games, entretenimento e finanças.",
                            Nome = "Sony",
                            PaisOrigem = "Japão",
                            Setor = "Tecnologia",
                            Slogan = "Make.Believe",
                            Website = "https://www.sony.com/"
                        },
                        new
                        {
                            Id = 4,
                            AnoFundacao = 1958,
                            Descricao = "Fornecedor global de produtos de eletrônicos de consumo, desde TVs até eletrodomésticos.",
                            Nome = "LG",
                            PaisOrigem = "Coreia do Sul",
                            Setor = "Tecnologia",
                            Slogan = "Life's Good",
                            Website = "https://www.lg.com/"
                        },
                        new
                        {
                            Id = 5,
                            AnoFundacao = 1975,
                            Descricao = "Uma das maiores empresas de software do mundo, com soluções em computação e nuvem.",
                            Nome = "Microsoft",
                            PaisOrigem = "EUA",
                            Setor = "Tecnologia",
                            Slogan = "Be what's next",
                            Website = "https://www.microsoft.com/"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
